### ISSUE TITLE
Clarify the purpose and benefits of vue-cordova

### ISSUE THREAD

**Issue by valnub** [kartsims/vue-cordova#10]
It seems like the documentation lacks to clearly state what the purpose/benefit of vue-cordova is and why developers should use it. Is it mandatory or optional to use with Vue and Cordova?

See https://twitter.com/macdonst/status/841104595334123520

**Comment by kartsims** [comment]
You're right, this is not the first person to get confused on the purpose of this library.

It is actually just a syntax helper but I am not sure how I should phrase it. Do you have any suggestion ?

**Comment by valnub** [comment]
I'm not sure if there is a correct terminology for a lib that only adds syntactic sugar :-)

**Comment by kartsims** [comment]
Haha I went for "syntax helper" then, and added a sidenote to the README :)
