### ISSUE TITLE
barcodesanner

### ISSUE THREAD

**Issue by dmlzj** [kartsims/vue-cordova#11]
Help me and thankyou!
How to use this plugin?
`cordova-plugin-barcodescanner`
[BarcodeScanner](https://github.com/hypery2k/cordova-barcodescanner-plugin)
I have run this:
`cordova plugin add cordova-plugin-barcodescanner --variable CAMERA_USAGE_DESCRIPTION="To scan barcodes"`
```js
Add a new plugin
1:Create a file named by the plugin in the plugins/ directory
2:Add your plugin to the list in src/index.js
3:Write a tiny doc in docs/_plugins/<plugin_name>.md
4:PR ;)
```
This 4 steps i don't know what i should do!

**Comment by kartsims** [comment]
Hi,

If you want to provide support for this plugin you can follow the 4 steps you mentioned. That means submitting a pull request afterwards.

Otherwise, you can use the plugin as stated in its documentation :
```
Vue.cordova.on('deviceready', function () {
  cordova.plugins.barcodeScanner...
})
```
