### ISSUE TITLE
How to add plugins?

### ISSUE THREAD

**Issue by qualisign** [kartsims/vue-cordova#13]
I'd like to use [file-opener2](https://github.com/pwlin/cordova-plugin-file-opener2 ) along with your plugin but I can't figure out how to add it to the list of known plugins.  How can I accomplish this?  Thanks.

**Comment by kartsims** [comment]
You can either use it with the global variables provided by the plugin

Or contribute by [adding the plugin to the supported plugins list](http://kartsims.github.io/vue-cordova/#documentationcontribute)

**Comment by gandhirajan** [comment]
Hi, When we try to access the fileopener2 plugin using cordova.plugins.fileOpener2 or Vue.cordova.plugins.fileOpener2 it doesnt work though. Could you please spare some time to check out this question - http://stackoverflow.com/questions/43629684/add-cordova-plugins-to-vue-cordova and let us know what exactly has gone wrong here or how to make use of this plugin in little more details? Thanks

**Comment by gandhirajan** [comment]
@kartsims  Could you please throw some light on this?
