### ISSUE TITLE
vue-cordova 和 ionic-native

### ISSUE THREAD

**Issue by small-carbon** [kartsims/vue-cordova#14]
我可以把vue-cordova 理解为是 ionic-native的实现思路（JS支持原生API调用）吗，只是ionic支持Angular（typescript），vue-cordova支持Vue

**Comment by kartsims** [comment]
Please make it in English, I don't speak Chinese

**Comment by small-carbon** [comment]
And [ionic-native](https://github.com/driftyco/ionic-native) (The successor to [ngCordova](https://github.com/driftyco/ng-cordova) ) implementation approach, only use Vue
