### ISSUE TITLE
http://kartsims.github.io/vue-cordova is problematic

### ISSUE THREAD

**Issue by evanoxu** [kartsims/vue-cordova#15]
Hey, guys.

why this url : http://kartsims.github.io/vue-cordova/css/style.css can open it new tab, but it can't load?

**Comment by kartsims** [comment]
Hi,

You are right I have experienced that before, I think it has something to do with Github servers.

When I open http://kartsims.github.io/vue-cordova/ it works fine. Does it on your computer ?

**Comment by evanoxu** [comment]
Nope, I can't open http://kartsims.github.io/vue-cordova/ , it jump to https://kartsims.github.io/vue-cordova/
