### ISSUE TITLE
About background

### ISSUE THREAD

**Issue by luizmagao** [kartsims/vue-cordova#29]
What's the reason css does not rotate the background image when placed in css?

**Comment by kartsims** [comment]
This issue should be brought up to Cordova, `vue-cordova` is just a wrapper for the cordova library.

**Comment by luizmagao** [comment]
Isso não é um problema do vue, e sim desse pacote. Como poderia fazer isso funcionar amigo? Me ajuda.

**Comment by kartsims** [comment]
je ne parle pas portugais

**Comment by luizmagao** [comment]
This is not a problem of the vue, but of this package. How could I make this work, my friend? Help me.
