### ISSUE TITLE
cordova-plugin-inappbrowser in vue-cordova

### ISSUE THREAD

**Issue by Jielde** [kartsims/vue-cordova#7]
Hi,

cordova-plugin-inappbrowser work with vue-cordova ?

Thx

**Comment by kartsims** [comment]
Hi,

Full plugins list : https://github.com/kartsims/vue-cordova/blob/master/PLUGINS.md

Will add many components soon, I need to dedicate some time to this project.

**Comment by Jielde** [comment]
ok, thx for response :)
